### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by SanderBoerdijk** [PotatoFi/Packet-Potato#25]
Hi, finally order me an packet potato, but got stuck with the programming (programming noob here, sorry in advance) when compiling I get the following error in IDE: Compilation error: "control reaches end of non-void function [-Werror=return-type]. I have tried several versions"  in the string_utils.cpp I have added a return 0 on line 84 (where the error occurs) and  upload and my potato works but I don't believe this is the right solution. what am i doing wrong?

```
byte getFrameType(wifi_promiscuous_pkt_type_t type)
{
  switch(type)
  {
    case WIFI_PKT_MGMT:
    return 0;

    case WIFI_PKT_CTRL:
    return 1;

    case WIFI_PKT_DATA:
    return 2;
  }
  return 0;
}
```

**Comment by PotatoFi** [comment]
Hey @SanderBoerdijk, sorry about the delay on this. Are you still having trouble with this?

**Comment by allynjcrowe** [comment]
hey Joel, I just tried to load 1.4 RC2, and I am having the same issue.

**Comment by PotatoFi** [comment]
@allynjcrowe Turns out that I fixed this ages ago, and never did a release! Oops!

[v1.4 is now released](https://github.com/PotatoFi/Packet-Potato/releases/tag/1.4). Enjoy!
